#+title: Literate emacs w/ Corgi for Clojure
#+PROPERTY: header-args:emacs-lisp :tangle ./init.el :mkdirp yes

* Welcome to ox's emacs config!


** Variables

#+begin_src emacs-lisp

;; NOTE: init.el is now generated from init.org.  Please edit that file
;;       in Emacs and init.el will be generated automatically!

;; You will most likely need to adjust this font size for your system!
(defvar efs/default-font-size 120)
(defvar efs/default-variable-font-size 120)

#+end_src
* Basic (Set-and-forget) Setup
** Tips for Use

In this document I've added links in many places that lead you to documentation for the various packages we use.  If you're looking at this file in Emacs, you can put your cursor on a link and press =C-c C-o= or run =M-x org-open-at-point= to open the link in your web browser.

** Straight.el package manager

Emacs has a built in package manager but it has a lot left to be desired. We're going to use straight.el and use-package combination here

#+begin_src emacs-lisp
;; Set up low-level stuff so we can install the various packages that make up
;; Corgi. Not super pretty, but you normally don't have to look at it.

;; Install the Straight package manager

(defvar bootstrap-version) 

(let ((install-url "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el")
      (bootstrap-file (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer (url-retrieve-synchronously install-url 'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

;; Install the use-package convenience macro

(straight-use-package 'use-package)

(setq straight-use-package-by-default t)

(when (not (file-exists-p (expand-file-name "straight/versions/default.el" straight-base-dir)))
  (straight-freeze-versions))

;; Enable the corgi-packages repository so we can install our packages with
;; Straight. This also runs some Corgi initialization code, notably copying over
;; Corgi's version file, so you get the same versions of packages that Corgi was
;; tested with.

(use-package corgi-packages
  :straight (corgi-packages
             :type git
             :host github
             :repo "corgi-emacs/corgi-packages"
             :branch "ox/separate-completion-ui"))

(add-to-list #'straight-recipe-repositories 'corgi-packages)
#+end_src

#+RESULTS:
| corgi-packages | org-elpa | melpa | gnu-elpa-mirror | el-get | emacsmirror-mirror |

** Exec path

Unfortunately emacs launched from =.app= launcher does not get the full exec path which our shell has. Let's fix that

#+begin_src emacs-lisp
  (use-package exec-path-from-shell
    :config
    (when (memq window-system '(mac ns x))
      (exec-path-from-shell-initialize)))
#+end_src

#+RESULTS:
: t

** Corgi emacs

#+begin_src emacs-lisp
(setq evil-want-C-u-scroll t)

(let ((straight-current-profile 'corgi))
  ;; Change a bunch of Emacs defaults, from disabling the menubar and toolbar,
  ;; to fixing modifier keys on Mac and disabling the system bell.
  (use-package corgi-defaults)

  ;; UI configuration for that Corgi-feel. This sets up a bunch of packages like
  ;; Evil, Smartparens, Projectile (project-aware commands) and Aggressive indent.
  (use-package corgi-editor)

  ;; The few custom commands that we ship with. This includes a few things we
  ;; emulate from Spacemacs, and commands for jumping to the user's init.el
  ;; (this file, with `SPC f e i'), or opening the user's key binding or signals
  ;; file.
  (use-package corgi-commands)

  ;; Extensive setup for a good Clojure experience, including clojure-mode,
  ;; CIDER, and a modeline indicator that shows which REPLs your evaluations go
  ;; to.
  ;; Also contains `corgi/cider-pprint-eval-register', bound to `,,', see
  ;; `set-register' calls below.
  (use-package corgi-clojure)

  (with-eval-after-load 'corgi-clojure (corgi/enable-cider-connection-indicator))
  

  ;; Emacs Lisp config, mainly to have a development experience that feels
  ;; similar to using CIDER and Clojure. (show results in overlay, threading
  ;; refactorings)
  (use-package corgi-emacs-lisp)

  ;; Change the color of the modeline based on the Evil state (e.g. green when
  ;; in insert state)
  (use-package corgi-stateline)

  ;; Package which provides corgi-keys and corgi-signals, the two files that
  ;; define all Corgi bindings, and the default files that Corkey will look for.
  (use-package corgi-bindings)

  ;; Corgi's keybinding system, which builds on top of Evil. See the manual, or
  ;; visit the key binding and signal files (with `SPC f e k', `SPC f e K', `SPC
  ;; f e s' `SPC f e S')
  ;; Put this last here, otherwise keybindings for commands that aren't loaded
  ;; yet won't be active.
  (use-package corkey
    :config 
    (corkey/load-and-watch)
    ;; Automatically pick up keybinding changes
    (corkey-mode 1)))
#+end_src

#+RESULTS:
: t

** Custom vars
#+begin_src emacs-lisp
(setq custom-file (concat user-emacs-directory "custom.el"))
(load custom-file 'noerror)
#+end_src

#+RESULTS:

** Keybinding Configuration

Main keybindings are configured using corkey. It supports easy keybindings for evil-mode. [[https://github.com/emacs-evil/evil-collection][evil-collection]] is used to automatically configure various Emacs modes with Vi-like keybindings for evil-mode.

#+begin_src emacs-lisp

;; Make ESC quit prompts
(global-set-key (kbd "<escape>") 'keyboard-escape-quit)

#+end_src

#+RESULTS:
: t

* Structural Editing
** treesitter
#+begin_src emacs-lisp

(use-package tree-sitter-langs
  :straight (tree-sitter-langs
             :host github :type git
             :repo "emacs-tree-sitter/tree-sitter-langs")
  :config
  (tree-sitter-load 'org)
  (tree-sitter-require 'org)
  (add-to-list 'tree-sitter-major-mode-language-alist '(org-mode . org))
  (global-tree-sitter-mode))

#+end_src
** symex
#+begin_src emacs-lisp
(use-package lispy)
(defun init-user-symex-conf ()
  (setq lispy-avy-keys (nconc (number-sequence ?a ?x)
                              (number-sequence ?A ?Z)
                              (number-sequence ?1 ?9)
                              '(?z)))
  (setq avy-keys (nconc (number-sequence ?a ?x)
                        (number-sequence ?A ?Z)
                        (number-sequence ?1 ?9)
                        '(?z)))
  (setq symex--user-evil-keyspec
        '(("j" . symex-go-up)
          ("k" . symex-go-down)
          ("s" . symex-go-forward)
          ("n" . symex-traverse-forward)
          ("N" . symex-traverse-forward-skip)
          ("C-w" . symex-wrap-square)
          ("M-w" . symex-wrap-curly)
          ("C-j" . symex-climb-branch)
          ("C-k" . symex-descend-branch)
          ("M-j" . symex-goto-highest)
          ("M-k" . symex-goto-lowest)
          ("." . symex-soar-forward)
          ("," . symex-soar-backward)
          ("r" . symex-replace)
          ("t" . (lambda () (interactive) (evil-set-jump) (lispy-ace-paren)))
          ("T" . (lambda () (interactive) (evil-set-jump) (call-interactively #'avy-goto-symbol-1)))
          ("C-t" . (lambda () (interactive) (signspice-with-mark 'lispy-ace-paren)))
          ("M-t" . (lambda () (interactive) (lispy-ace-paren 2)))
          ("M-T" . (lambda () (interactive) (signspice-with-mark 'lispy-ace-paren 2)))
          ("M-r" . cljr-raise-sexp)
          ("M-R" . lispy-raise-some)
          ("C-e" . signspice-eval-mark)
          ("z" . evil-scroll-line-to-top)
          ("C-u" . signspice-goto-previous-mark)
          ("<tab>" . origami-toggle-node)
          ("<backtab>" . evil-show-marks)
          ("C-d" . cider-pprint-eval-defun-at-point)
          ("C-p" . signspice-pprint-at-point)
          ("C-s-p" . portal.api/open)
          ("C-S-s-p" . portal-copy)
          ("M-p" . signspice-steal-from-ace)))
  (symex-initialize)
  (setq evil-symex-state-cursor '("#884444" box))
  (setq evil-normal-state-cursor 'hollow-rectangle)

  (defun load-symex-branch ()
    "switch active symex branch"
    (interactive)
    (save-excursion
      (let* ((symex-repo-buf (find-file "~/projects/symex.el/.projectile")))
        (with-current-buffer symex-repo-buf
          (magit-branch-checkout (car (completing-read-multiple "select branch: " '("master" "symex-ts-integration"))))))
      (funcall-interactively #'straight-normalize-package (require 'symex))
      (funcall-interactively #'straight-rebuild-package "symex")
      (let* ((symex-features '(symex-transformations
                               symex-transformations-lisp
                               symex-transformations-ts)))
        (dolist (symex-feature symex-features)
          (when (member symex-feature features)
            (unload-feature symex-feature t))))
      ;; trick require to reload symex. (before, I had unloaded all these;
      ;; but somehow one of them unloads a bunch of other features not in the list. not sure why.)
      (setf features (cl-remove-if (lambda (feature) (string-prefix-p "symex" (cl-prin1-to-string feature))) features))
      (require 'symex))))

;; (use-package symex
;;   :straight (symex-main
;;              :type git
;;              :host github
;;              :repo "countvajhula/symex.el")
;;   :config
;;   (init-user-symex-conf))

(use-package symex
  :straight (symex
             :type git
             :host github
             :repo "SignSpice/symex.el"
             :local-repo "~/projects/symex.el")
  :config 
  (init-user-symex-conf))

#+end_src
** combobulate
#+begin_src emacs-lisp
(use-package combobulate
  :straight '(combobulate
              :host github
              :type git
              :repo "mickeynp/combobulate")
  ;; Ensure `combobulate-mode` is activated when you launch a mode it supports
  :hook ((python-mode . combobulate-mode)
         (js-mode . combobulate-mode)
         (typescript-mode . combobulate-mode)))
#+end_src
* Evil
** Base config

#+begin_src emacs-lisp

(use-package evil
  :init
  (setq evil-want-integration t)
  (setq evil-want-keybinding nil)
  (setq evil-want-C-i-jump nil)
  (fset 'evil-visual-update-x-selection 'ignore)
  (setq evil-kill-on-visual-paste nil)
  (setq evil-insert-state-cursor '(bar "green"))
  (setq-default evil-symbol-word-search t)
  :config
  (evil-mode 1)
  (define-key evil-insert-state-map (kbd "C-g") 'evil-normal-state)

  (define-key evil-insert-state-map (kbd "C-h") 'evil-delete-backward-char-and-join)

  ;; Use visual line motions even outside of visual-line-mode buffers
  (evil-global-set-key 'motion "j" 'evil-next-visual-line)
  (evil-global-set-key 'motion "k" 'evil-previous-visual-line)

  (evil-set-initial-state 'messages-buffer-mode 'normal)
  (evil-set-initial-state 'dashboard-mode 'normal))

#+end_src

#+RESULTS:
: t

** Evil collection

#+begin_src emacs-lisp

  (use-package evil-collection
    :after evil
    :config
    (evil-collection-init))

#+end_src

** Evil cleverparens

#+begin_src emacs-lisp
  (use-package evil-cleverparens
    :after (evil smartparens)
    :commands evil-cleverparens-mode
    :init
    (add-hook 'clojure-mode-hook #'evil-cleverparens-mode)
    (add-hook 'emacs-lisp-mode-hook #'evil-cleverparens-mode)
    (setq evil-cleverparens-complete-parens-in-yanked-region t)
    :config
    (setq evil-cleverparens-use-s-and-S nil)
    (evil-define-key '(normal visual) evil-cleverparens-mode-map
      "s" nil
      "S" nil
      "{" nil
      "}" nil
      "[" nil
      "]" nil
      (kbd "<tab>") 'evil-jump-item))
#+end_src

* UI Configuration

** Basic UI Configuration

This section configures basic UI settings that remove unneeded elements to make Emacs look a lot more minimal and modern.  If you're just getting started in Emacs, the menu bar might be helpful so you can remove the =(menu-bar-mode -1)= line if you'd like to still see that.

#+begin_src emacs-lisp

  (setq inhibit-startup-message t)

  (scroll-bar-mode -1)        ; Disable visible scrollbar
  (tool-bar-mode -1)          ; Disable the toolbar
  (tooltip-mode -1)           ; Disable tooltips
  (set-fringe-mode 10)        ; Give some breathing room

  (menu-bar-mode -1)            ; Disable the menu bar

  ;; Set up the visible bell
  (setq visible-bell t)

  (column-number-mode)
  ;; disable line numbers completely
  (global-display-line-numbers-mode 0)

  ;; Disable line numbers for some modes
  (dolist (mode '(org-mode-hook
                  term-mode-hook
                  shell-mode-hook
                  eshell-mode-hook))
    (add-hook mode (lambda () (display-line-numbers-mode 0))))

#+end_src

#+RESULTS:

** Workspaces
#+begin_src emacs-lisp
(use-package bufler
:straight '(bufler
:type git
:host github
:repo "alphapapa/bufler.el"))
#+end_src

** Font Configuration

=Iosevka= gang assemble!

#+begin_src emacs-lisp

  (set-face-attribute 'default nil :font "Iosevka" :height efs/default-font-size)

  ;; Set the fixed pitch face
  (set-face-attribute 'fixed-pitch nil :font "Iosevka" :height efs/default-font-size)

  ;; Set the variable pitch face
  ;; (set-face-attribute 'variable-pitch nil :font "Times New Roman" :height efs/default-font-size :weight 'regular)
  (set-face-attribute 'variable-pitch nil :font "Iosevka" :height efs/default-font-size :weight 'regular)

#+end_src

#+RESULTS:

** Command Log Mode

[[https://github.com/lewang/command-log-mode][command-log-mode]] is useful for displaying a panel showing each key binding you use in a panel on the right side of the frame.  Great for live streams and screencasts!

#+begin_src emacs-lisp

(use-package command-log-mode)

#+end_src

** Color Theme

[[https://github.com/hlissner/emacs-doom-themes][doom-themes]] is a great set of themes with a lot of variety and support for many different Emacs modes.  Taking a look at the [[https://github.com/hlissner/emacs-doom-themes/tree/screenshots][screenshots]] might help you decide which one you like best.  You can also run =M-x counsel-load-theme= to choose between them easily.

#+begin_src emacs-lisp

  (use-package doom-themes
    :init (load-theme 'doom-dracula t))

  (use-package cherry-blossom-theme
    :config
    (load-theme 'cherry-blossom t))
#+end_src

#+RESULTS:
: t

** Better Modeline

[[https://github.com/seagle0128/doom-modeline][doom-modeline]] is a very attractive and rich (yet still minimal) mode line configuration for Emacs.  The default configuration is quite good but you can check out the [[https://github.com/seagle0128/doom-modeline#customize][configuration options]] for more things you can enable or disable.

*NOTE:* The first time you load your configuration on a new machine, you'll need to run `M-x all-the-icons-install-fonts` so that mode line icons display correctly.

#+begin_src emacs-lisp

(use-package all-the-icons)

(use-package doom-modeline
  :init (doom-modeline-mode 1)
  :custom ((doom-modeline-height 8)))

#+end_src

** Which Key

[[https://github.com/justbur/emacs-which-key][which-key]] is a useful UI panel that appears when you start pressing any key binding in Emacs to offer you all possible completions for the prefix.  For example, if you press =C-c= (hold control and press the letter =c=), a panel will appear at the bottom of the frame displaying all of the bindings under that prefix and which command they run.  This is very useful for learning the possible key bindings in the mode of your current buffer.

#+begin_src emacs-lisp

(use-package which-key
  :init (which-key-mode)
  :diminish which-key-mode
  :config
  (setq which-key-idle-delay .1))

#+end_src

** Vertico

#+begin_src emacs-lisp
(use-package vertico
  :init
  (vertico-mode)

  ;; Different scroll margin
  ;; (setq vertico-scroll-margin 0)

  ;; Show more candidates
  ;; (setq vertico-count 20)

  ;; Grow and shrink the Vertico minibuffer
  ;; (setq vertico-resize t)

  ;; Optionally enable cycling for `vertico-next' and `vertico-previous'.
  ;; (setq vertico-cycle t)
  )

;; Persist history over Emacs restarts. Vertico sorts by history position.
(use-package savehist
  :init
  (savehist-mode))

;; A few more useful configurations...
(use-package emacs
  :init
  ;; Add prompt indicator to `completing-read-multiple'.
  ;; We display [CRM<separator>], e.g., [CRM,] if the separator is a comma.
  (defun crm-indicator (args)
    (cons (format "[CRM%s] %s"
                  (replace-regexp-in-string
                   "\\`\\[.*?]\\*\\|\\[.*?]\\*\\'" ""
                   crm-separator)
                  (car args))
          (cdr args)))
  (advice-add #'completing-read-multiple :filter-args #'crm-indicator)

  ;; Do not allow the cursor in the minibuffer prompt
  (setq minibuffer-prompt-properties
        '(read-only t cursor-intangible t face minibuffer-prompt))
  (add-hook 'minibuffer-setup-hook #'cursor-intangible-mode)

  ;; Emacs 28: Hide commands in M-x which do not work in the current mode.
  ;; Vertico commands are hidden in normal buffers.
  ;; (setq read-extended-command-predicate
  ;;       #'command-completion-default-include-p)

  ;; Enable recursive minibuffers
  (setq enable-recursive-minibuffers t))

;; Optionally use the `orderless' completion style.
(use-package orderless
  :init
  ;; Configure a custom style dispatcher (see the Consult wiki)
  ;; (setq orderless-style-dispatchers '(+orderless-dispatch)
  ;;       orderless-component-separator #'orderless-escapable-split-on-space)
  (setq completion-styles '(orderless basic)
        completion-category-defaults nil
        completion-category-overrides '((file (styles partial-completion)))))
#+end_src

#+RESULTS:

** Consult

#+begin_src emacs-lisp
;; Example configuration for Consult
(use-package consult
  ;; Replace bindings. Lazily loaded due by `use-package'.
  :bind (;; C-c bindings (mode-specific-map)
         ("C-c h" . consult-history)
         ("C-c m" . consult-mode-command)
         ("C-c k" . consult-kmacro)
         ;; C-x bindings (ctl-x-map)
         ("C-x M-:" . consult-complex-command)     ;; orig. repeat-complex-command
         ("C-x b" . consult-buffer)                ;; orig. switch-to-buffer
         ("C-x 4 b" . consult-buffer-other-window) ;; orig. switch-to-buffer-other-window
         ("C-x 5 b" . consult-buffer-other-frame)  ;; orig. switch-to-buffer-other-frame
         ("C-x r b" . consult-bookmark)            ;; orig. bookmark-jump
         ("C-x p b" . consult-project-buffer)      ;; orig. project-switch-to-buffer
         ;; Custom M-# bindings for fast register access
         ("M-#" . consult-register-load)
         ("M-'" . consult-register-store)          ;; orig. abbrev-prefix-mark (unrelated)
         ("C-M-#" . consult-register)
         ;; Other custom bindings
         ("M-y" . consult-yank-pop)                ;; orig. yank-pop
         ("<help> a" . consult-apropos)            ;; orig. apropos-command
         ;; M-g bindings (goto-map)
         ("M-g e" . consult-compile-error)
         ("M-g f" . consult-flymake)               ;; Alternative: consult-flycheck
         ("M-g g" . consult-goto-line)             ;; orig. goto-line
         ("M-g M-g" . consult-goto-line)           ;; orig. goto-line
         ("M-g o" . consult-outline)               ;; Alternative: consult-org-heading
         ("M-g m" . consult-mark)
         ("M-g k" . consult-global-mark)
         ("M-g i" . consult-imenu)
         ("M-g I" . consult-imenu-multi)
         ;; M-s bindings (search-map)
         ("M-s d" . consult-find)
         ("M-s D" . consult-locate)
         ("M-s g" . consult-grep)
         ("M-s G" . consult-git-grep)
         ("M-s r" . consult-ripgrep)
         ("M-s l" . consult-line)
         ("M-s L" . consult-line-multi)
         ("M-s m" . consult-multi-occur)
         ("M-s k" . consult-keep-lines)
         ("M-s u" . consult-focus-lines)
         ;; Isearch integration
         ("M-s e" . consult-isearch-history)
         :map isearch-mode-map
         ("M-e" . consult-isearch-history)         ;; orig. isearch-edit-string
         ("M-s e" . consult-isearch-history)       ;; orig. isearch-edit-string
         ("M-s l" . consult-line)                  ;; needed by consult-line to detect isearch
         ("M-s L" . consult-line-multi)            ;; needed by consult-line to detect isearch
         ;; Minibuffer history
         :map minibuffer-local-map
         ("M-s" . consult-history)                 ;; orig. next-matching-history-element
         ("M-r" . consult-history))                ;; orig. previous-matching-history-element

  ;; Enable automatic preview at point in the *Completions* buffer. This is
  ;; relevant when you use the default completion UI.
  :hook (completion-list-mode . consult-preview-at-point-mode)

  ;; The :init configuration is always executed (Not lazy)
  :init

  ;; Optionally configure the register formatting. This improves the register
  ;; preview for `consult-register', `consult-register-load',
  ;; `consult-register-store' and the Emacs built-ins.
  (setq register-preview-delay 0.5
        register-preview-function #'consult-register-format)

  ;; Optionally tweak the register preview window.
  ;; This adds thin lines, sorting and hides the mode line of the window.
  (advice-add #'register-preview :override #'consult-register-window)

  ;; Use Consult to select xref locations with preview
  (setq xref-show-xrefs-function #'consult-xref
        xref-show-definitions-function #'consult-xref)

  ;; Configure other variables and modes in the :config section,
  ;; after lazily loading the package.
  :config

  ;; Optionally configure preview. The default value
  ;; is 'any, such that any key triggers the preview.
  ;; (setq consult-preview-key 'any)
  ;; (setq consult-preview-key (kbd "M-."))
  ;; (setq consult-preview-key (list (kbd "<S-down>") (kbd "<S-up>")))
  ;; For some commands and buffer sources it is useful to configure the
  ;; :preview-key on a per-command basis using the `consult-customize' macro.
  (consult-customize
   consult-theme
   :preview-key '(:debounce 0.2 any)
   consult-ripgrep consult-git-grep consult-grep
   consult-bookmark consult-recent-file consult-xref
   consult--source-bookmark consult--source-recent-file
   consult--source-project-recent-file
   :preview-key (kbd "M-."))

  ;; Optionally configure the narrowing key.
  ;; Both < and C-+ work reasonably well.
  (setq consult-narrow-key "<") ;; (kbd "C-+")

  ;; Optionally make narrowing help available in the minibuffer.
  ;; You may want to use `embark-prefix-help-command' or which-key instead.
  ;; (define-key consult-narrow-map (vconcat consult-narrow-key "?") #'consult-narrow-help)

  ;; By default `consult-project-function' uses `project-root' from project.el.
  ;; Optionally configure a different project root function.
  ;; There are multiple reasonable alternatives to chose from.
  ;;;; 1. project.el (the default)
  ;; (setq consult-project-function #'consult--default-project--function)
  ;;;; 2. projectile.el (projectile-project-root)
  ;; (autoload 'projectile-project-root "projectile")
  ;; (setq consult-project-function (lambda (_) (projectile-project-root)))
  ;;;; 3. vc.el (vc-root-dir)
  ;; (setq consult-project-function (lambda (_) (vc-root-dir)))
  ;;;; 4. locate-dominating-file
  ;; (setq consult-project-function (lambda (_) (locate-dominating-file "." ".git")))
)
#+end_src

#+RESULTS:
: consult-history

** Helpful Help Commands

[[https://github.com/Wilfred/helpful][Helpful]] adds a lot of very helpful (get it?) information to Emacs' =describe-= command buffers.  For example, if you use =describe-function=, you will not only get the documentation about the function, you will also see the source code of the function and where it gets used in other places in the Emacs configuration.  It is very useful for figuring out how things work in Emacs.

#+begin_src emacs-lisp

  (use-package helpful
    :custom
    (counsel-describe-function-function #'helpful-callable)
    (counsel-describe-variable-function #'helpful-variable)
    :bind
    ([remap describe-function] . counsel-describe-function)
    ([remap describe-command] . helpful-command)
    ([remap describe-variable] . counsel-describe-variable)
    ([remap describe-key] . helpful-key))

#+end_src

** Rainbow Delimiters

[[https://github.com/Fanael/rainbow-delimiters][rainbow-delimiters]] is useful in programming modes because it colorizes nested parentheses and brackets according to their nesting depth.  This makes it a lot easier to visually match parentheses in Emacs Lisp code without having to count them yourself.

#+begin_src emacs-lisp

(use-package rainbow-delimiters
  :hook (prog-mode . rainbow-delimiters-mode))

#+end_src

* Org Mode

[[https://orgmode.org/][Org Mode]] is one of the hallmark features of Emacs.  It is a rich document editor, project planner, task and time tracker, blogging engine, and literate coding utility all wrapped up in one package.

** Better Font Faces

The =efs/org-font-setup= function configures various text faces to tweak the sizes of headings and use variable width fonts in most cases so that it looks more like we're editing a document in =org-mode=.  We switch back to fixed width (monospace) fonts for code blocks and tables so that they display correctly.

#+begin_src emacs-lisp

  (defun efs/org-font-setup ()
    ;; Replace list hyphen with dot
    (font-lock-add-keywords 'org-mode
                            '(("^ *\\([-]\\) "
                               (0 (prog1 () (compose-region (match-beginning 1) (match-end 1) "•"))))))

    ;; Set faces for heading levels
    (dolist (face '((org-level-1 . 1.2)
                    (org-level-2 . 1.1)
                    (org-level-3 . 1.05)
                    (org-level-4 . 1.0)
                    (org-level-5 . 1.1)
                    (org-level-6 . 1.1)
                    (org-level-7 . 1.1)
                    (org-level-8 . 1.1))))

    ;; Ensure that anything that should be fixed-pitch in Org files appears that way
    (set-face-attribute 'org-block nil :foreground nil :inherit 'fixed-pitch)
    (set-face-attribute 'org-code nil   :inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-table nil   :inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-verbatim nil :inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-special-keyword nil :inherit '(font-lock-comment-face fixed-pitch))
    (set-face-attribute 'org-meta-line nil :inherit '(font-lock-comment-face fixed-pitch))
    (set-face-attribute 'org-checkbox nil :inherit 'fixed-pitch))

#+end_src

#+RESULTS:
: efs/org-font-setup

** Basic Config

This section contains the basic configuration for =org-mode= plus the configuration for Org agendas and capture templates.  There's a lot to unpack in here so I'd recommend watching the videos for [[https://youtu.be/VcgjTEa0kU4][Part 5]] and [[https://youtu.be/PNE-mgkZ6HM][Part 6]] for a full explanation.

#+begin_src emacs-lisp
(defun efs/org-mode-setup ()
  (org-indent-mode)
  (variable-pitch-mode 1)
  (visual-line-mode 1))

(use-package org
  :hook (org-mode . efs/org-mode-setup)
  :config
  (setq org-ellipsis " ▾")

  (setq org-edit-src-content-indentation 0)

  (setq org-agenda-start-with-log-mode t)
  (setq org-log-done 'time)
  (setq org-log-into-drawer t)

  (setq org-agenda-files 
        '("~/org/personal/todo.org"
          "~/org/personal/inbox.org"))

  (require 'org-habit)
  (add-to-list 'org-modules 'org-habit)
  (setq org-habit-graph-column 60)

  (setq org-todo-keywords
        '((sequence "TODO(t)" "NEXT(n)" "|" "DONE(d!)")
          (sequence "BACKLOG(b)" "PLAN(p)" "READY(r)" "ACTIVE(a)" "REVIEW(v)" "WAIT(w@/!)" "HOLD(h)" "|" "COMPLETED(c)" "CANC(k@)")))

  (setq org-refile-targets
        '(("Archive.org" :maxlevel . 1)
          ("Tasks.org" :maxlevel . 1)))

  ;; Save Org buffers after refiling!
  (advice-add 'org-refile :after 'org-save-all-org-buffers)

  (setq org-tag-alist
        '((:startgroup)
                                        ; Put mutually exclusive tags here
          (:endgroup)
          ("@errand" . ?E)
          ("@home" . ?H)
          ("@work" . ?W)
          ("agenda" . ?a)
          ("planning" . ?p)
          ("publish" . ?P)
          ("batch" . ?b)
          ("note" . ?n)
          ("idea" . ?i)))

  ;; Configure custom agenda views
  (setq org-agenda-custom-commands
        '(("d" "Dashboard"
           ((agenda "" ((org-deadline-warning-days 7)))
            (todo "NEXT"
                  ((org-agenda-overriding-header "Next Tasks")))
            (tags-todo "agenda/ACTIVE" ((org-agenda-overriding-header "Active Projects")))))

          ("n" "Next Tasks"
           ((todo "NEXT"
                  ((org-agenda-overriding-header "Next Tasks")))))

          ("W" "Work Tasks" tags-todo "+work-email")

          ;; Low-effort next actions
          ("e" tags-todo "+TODO=\"NEXT\"+Effort<15&+Effort>0"
           ((org-agenda-overriding-header "Low Effort Tasks")
            (org-agenda-max-todos 20)
            (org-agenda-files org-agenda-files)))

          ("w" "Workflow Status"
           ((todo "WAIT"
                  ((org-agenda-overriding-header "Waiting on External")
                   (org-agenda-files org-agenda-files)))
            (todo "REVIEW"
                  ((org-agenda-overriding-header "In Review")
                   (org-agenda-files org-agenda-files)))
            (todo "PLAN"
                  ((org-agenda-overriding-header "In Planning")
                   (org-agenda-todo-list-sublevels nil)
                   (org-agenda-files org-agenda-files)))
            (todo "BACKLOG"
                  ((org-agenda-overriding-header "Project Backlog")
                   (org-agenda-todo-list-sublevels nil)
                   (org-agenda-files org-agenda-files)))
            (todo "READY"
                  ((org-agenda-overriding-header "Ready for Work")
                   (org-agenda-files org-agenda-files)))
            (todo "ACTIVE"
                  ((org-agenda-overriding-header "Active Projects")
                   (org-agenda-files org-agenda-files)))
            (todo "COMPLETED"
                  ((org-agenda-overriding-header "Completed Projects")
                   (org-agenda-files org-agenda-files)))
            (todo "CANC"
                  ((org-agenda-overriding-header "Cancelled Projects")
                   (org-agenda-files org-agenda-files)))))))

  (setq org-capture-templates
        `(("t" "Tasks / Projects")
          ("tt" "Task" entry (file+olp "~/Projects/Code/emacs-from-scratch/OrgFiles/Tasks.org" "Inbox")
           "* TODO %?\n  %U\n  %a\n  %i" :empty-lines 1)

          ("j" "Journal Entries")
          ("jj" "Journal" entry
           (file+olp+datetree "~/Projects/Code/emacs-from-scratch/OrgFiles/Journal.org")
           "\n* %<%I:%M %p> - Journal :journal:\n\n%?\n\n"
           ;; ,(dw/read-file-as-string "~/Notes/Templates/Daily.org")
           :clock-in :clock-resume
           :empty-lines 1)
          ("jm" "Meeting" entry
           (file+olp+datetree "~/Projects/Code/emacs-from-scratch/OrgFiles/Journal.org")
           "* %<%I:%M %p> - %a :meetings:\n\n%?\n\n"
           :clock-in :clock-resume
           :empty-lines 1)

          ("w" "Workflows")
          ("we" "Checking Email" entry (file+olp+datetree "~/Projects/Code/emacs-from-scratch/OrgFiles/Journal.org")
           "* Checking Email :email:\n\n%?" :clock-in :clock-resume :empty-lines 1)

          ("m" "Metrics Capture")
          ("mw" "Weight" table-line (file+headline "~/Projects/Code/emacs-from-scratch/OrgFiles/Metrics.org" "Weight")
           "| %U | %^{Weight} | %^{Notes} |" :kill-buffer t)))

  (define-key global-map (kbd "C-c j")
              (lambda () (interactive) (org-capture nil "jj")))

  (efs/org-font-setup))

#+end_src

#+RESULTS:
| (lambda nil (add-hook 'after-save-hook #'efs/org-babel-tangle-config)) | org-tempo-setup | org-bullets-mode | er/add-org-mode-expansions | #[0 \300\301\302\303\304$\207 [add-hook change-major-mode-hook org-fold-show-all append local] 5] | #[0 \300\301\302\303\304$\207 [add-hook change-major-mode-hook org-babel-show-result-all append local] 5] | org-babel-result-hide-spec | org-babel-hide-all-hashes | #[0 \301\211\207 [imenu-create-index-function org-imenu-get-tree] 2] | efs/org-mode-visual-fill | efs/org-mode-setup | (lambda nil (display-line-numbers-mode 0)) |

*** Nicer Heading Bullets

[[https://github.com/sabof/org-bullets][org-bullets]] replaces the heading stars in =org-mode= buffers with nicer looking characters that you can control.  Another option for this is [[https://github.com/integral-dw/org-superstar-mode][org-superstar-mode]] which we may cover in a later video.

#+begin_src emacs-lisp

  (use-package org-bullets
    :after org
    :hook (org-mode . org-bullets-mode)
    :custom
    (org-bullets-bullet-list '("◉" "○" "●" "○" "●" "○" "●")))

#+end_src

*** Center Org Buffers

We use [[https://github.com/joostkremers/visual-fill-column][visual-fill-column]] to center =org-mode= buffers for a more pleasing writing experience as it centers the contents of the buffer horizontally to seem more like you are editing a document.  This is really a matter of personal preference so you can remove the block below if you don't like the behavior.

#+begin_src emacs-lisp

  (defun efs/org-mode-visual-fill ()
    (setq visual-fill-column-width 100
          visual-fill-column-center-text t)
    (visual-fill-column-mode 1))

  (use-package visual-fill-column
    :hook (org-mode . efs/org-mode-visual-fill))

#+end_src

** Configure Babel Languages

To execute or export code in =org-mode= code blocks, you'll need to set up =org-babel-load-languages= for each language you'd like to use.  [[https://orgmode.org/worg/org-contrib/babel/languages.html][This page]] documents all of the languages that you can use with =org-babel=.

#+begin_src emacs-lisp

  (org-babel-do-load-languages
    'org-babel-load-languages
    '((emacs-lisp . t)
      (python . t)))

  (push '("conf-unix" . conf-unix) org-src-lang-modes)
  (setq org-confirm-babel-evaluate nil)

#+end_src

** Org easy templates

You can disable it in favor of yasnippets

#+begin_src emacs-lisp
  (add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
  (add-to-list 'org-structure-template-alist '("sh" . "src sh"))
  (require 'org-tempo)
#+end_src

#+RESULTS:
: org-tempo

** Org Denote

#+begin_src emacs-lisp

(use-package denote
  :config
  (setq denote-directory "~/org")

  (setq denote-known-keywords '("journal" "projects" "ideas"
                                "people" "book" "psychology"
                                "thoughts"))
  ;; (setq denote-prompts '(title subdirectory))

  ;; Buttonize all denote links in text buffers
  (add-hook 'find-file-hook #'denote-link-buttonize-buffer)
  (require 'denote-dired)
  (add-hook 'dired-mode-hook #'denote-dired-mode))

;; Fontify file names in Dired

(with-eval-after-load 'org-capture
  (require 'denote-org-capture)
  (add-to-list 'org-capture-templates
               '("n" "New note (with Denote)" plain
                 (file denote-last-path)
                 #'denote-org-capture
                 :no-save t
                 :immediate-finish nil
                 :kill-buffer t
                 :jump-to-captured t)))

(with-eval-after-load 'denote
  (defun my-denote-journal ()
    "Create an entry tagged 'journal' with the date as its title."
    (interactive)
    (denote
     (format-time-string "%A %e %B %Y")  ; format like Tuesday 14 June 2022
     '("journal")
     nil
     "~/Denotes/Journal")

    (insert "* Thoughts\n\n* Tasks\n\n")))

(with-eval-after-load 'denote
  (defun my-denote-journal ()
    "Create an entry tagged 'journal' with the date as its title."
    (interactive)
    (denote
     (format-time-string "%A %e %B %Y")  ; format like Tuesday 14 June 2022
     '("journal")
     nil
     "~/Denotes/Journal")

    (insert "* Thoughts\n\n* Tasks\n\n"))) ; multiple keywords are a list of strings: '("one" "two"))
#+end_src

** Evil Org (temp)
#+begin_src emacs-lisp
(use-package evil-org)
#+end_src

** Optional finds

Most of these are disabled for now, but I find some cool awesome stuff from over the interwebz and this is the place to save those

#+begin_src emacs-lisp :tangle no
  (add-hook 'org-mode-hook '(lambda () (setq fill-column 80)))
  (add-hook 'org-mode-hook 'turn-on-auto-fill)
  (add-hook 'org-mode-hook 'auto-fill-mode)
#+end_src

* Literate configuration with init.org
** Auto-tangle Configuration Files

This snippet adds a hook to =org-mode= buffers so that =efs/org-babel-tangle-config= gets executed each time such a buffer gets saved.  This function checks to see if the file being saved is the Emacs.org file you're looking at right now, and if so, automatically exports the configuration here to the associated output files.

#+begin_src emacs-lisp

  ;; Automatically tangle our Emacs.org config file when we save it
  (defun efs/org-babel-tangle-config ()
    (when (or 
           (string-equal buffer-file-name
                         (expand-file-name (concat user-emacs-directory "init.org")))
           (string-equal buffer-file-name
                         (file-truename
                          (expand-file-name (concat user-emacs-directory "init.org")))))
      ;; Dynamic scoping to the rescue
      (let ((org-confirm-babel-evaluate nil))
        (org-babel-tangle))))

  (add-hook 'org-mode-hook (lambda () (add-hook 'after-save-hook #'efs/org-babel-tangle-config)))

#+end_src

#+RESULTS:
| er/add-org-mode-expansions | #[0 \301\211\207 [imenu-create-index-function org-imenu-get-tree] 2] | (lambda nil (add-hook 'after-save-hook #'efs/org-babel-tangle-config)) | org-bullets-mode | #[0 \300\301\302\303\304$\207 [add-hook change-major-mode-hook org-show-all append local] 5] | #[0 \300\301\302\303\304$\207 [add-hook change-major-mode-hook org-babel-show-result-all append local] 5] | org-babel-result-hide-spec | org-babel-hide-all-hashes | efs/org-mode-visual-fill | efs/org-mode-setup | (lambda nil (display-line-numbers-mode 0)) |

** Open init.org function
#+begin_src emacs-lisp
  (defun ox/open-init-org ()
    (interactive)
      (find-file (expand-file-name "init.org" user-emacs-directory)))
#+end_src

#+RESULTS:
: ox/open-init-org
** If you're sturggling to get tangling to work

Add this into init.el and then `M-x eval-buffer`

#+begin_src emacs-lisp :tangle no
(require 'org)
(org-babel-load-file
 (expand-file-name "init.org" user-emacs-directory))
#+end_src

* Projectile

[[https://projectile.mx/][Projectile]] is a project management library for Emacs which makes it a lot easier to navigate around code projects for various languages.  Many packages integrate with Projectile so it's a good idea to have it installed even if you don't use its commands directly.

#+begin_src emacs-lisp

  (use-package projectile
    :diminish projectile-mode
    :config (projectile-mode)
    ;; :custom ((projectile-completion-system 'ivy))
    :bind-keymap
    ("C-c p" . projectile-command-map)
    :init
    ;; NOTE: Set this to the folder where you keep your Git repos!
    (when (file-directory-p "~/projects")
      (setq projectile-project-search-path '("~/projects")))
    (setq projectile-switch-project-action #'projectile-dired))

#+end_src

** Refresh directory

#+begin_src emacs-lisp
  (defun ox/refresh-projects-dir ()
    (interactive)
    (projectile-discover-projects-in-directory "~/projects"))
#+end_src

* Magit

[[https://magit.vc/][Magit]] is the best Git interface I've ever used.  Common Git operations are easy to execute quickly using Magit's command panel system.

#+begin_src emacs-lisp

  (use-package magit
    :config
  ;; (setq magit-display-buffer-function #'magit-display-buffer-fullframe-status-v1)
    :custom
    (magit-display-buffer-function #'magit-display-buffer-same-window-except-diff-v1))

  ;; NOTE: Make sure to configure a GitHub token before using this package!
  ;; - https://magit.vc/manual/forge/Token-Creation.html#Token-Creation
  ;; - https://magit.vc/manual/ghub/Getting-Started.html#Getting-Started
  (use-package forge)

#+end_src

** Delta - better diffing
#+begin_src ig-emacs-lisp
(use-package magit-delta
  :after (magit)
  :config
  (add-hook 'magit-mode-hook (lambda () (magit-delta-mode +1))))
#+end_src

* Git link
#+begin_src emacs-lisp
  (use-package git-link
    :config
    (setq git-link-open-in-browser t
          git-link-use-commit t))
#+end_src

#+RESULTS:
: t

* Verb HTTP rest client
#+begin_src emacs-lisp
  (use-package verb)
  (use-package org
    :config (define-key org-mode-map (kbd "C-c C-r") verb-command-map))
#+end_src

#+RESULTS:
: t

* Snippets
yasnippets is the most complete and popular snippet engine which works based on major-modes

#+begin_src emacs-lisp
(use-package yasnippet-snippets
  :ensure t)
(use-package yasnippet
  :ensure t
  :config (yas-global-mode 1))
#+end_src

#+RESULTS:
: t

* Markdown & Yaml

#+begin_src emacs-lisp
(use-package markdown-mode)
(use-package yaml-mode)
#+end_src

* Javascript 

#+begin_src emacs-lisp
;; REPL-driven development for JavaScript, included as an example of how to
;; configure signals, see `user-signal.el' (visit it with `SPC f e s')
(use-package js-comint)

(use-package js2-mode
  :mode "\\.js\\'"
  :config
  (customize-set-variable 'js2-basic-offset 2)
  (customize-set-variable 'js2-include-node-externs t))

(add-hook 'js2-mode-hook #'js2-imenu-extras-mode)

(use-package tide
  :after (company flycheck)
  :config
  (define-key tide-mode-map (kbd "s-b") 'tide-jump-to-definition)
  (define-key tide-mode-map (kbd "s-[") 'tide-jump-back))
#+end_src

#+RESULTS:
: t

* Emacs server

Start the emacs-server, so you can open files from the command line with
`emacsclient -n <file>' (we like to put `alias en="emacsclient -n"' in our shell
config).

#+begin_src emacs-lisp
(server-start)
#+end_src

* Register shortcuts

Emacs has "registers", places to keep small snippets of text. We make it easy to run a snippet of Clojure code in such a register, just press comma twice followed by the letter that designates the register (while in a Clojure buffer with a connected REPL). The code will be evaluated, and the result pretty-printed to a separate buffer.

By starting a snippet with =#_clj= or =#_cljs= you can control which type of REPL it will go to, in case you have both a CLJ and a CLJS REPL connected.

#+begin_src emacs-lisp
(set-register ?k "#_clj (do (require 'kaocha.repl) (kaocha.repl/run))")
(set-register ?K "#_clj (do (require 'kaocha.repl) (kaocha.repl/run-all))")
(set-register ?r "#_clj (do (require 'user :reload) (user/reset))")
(set-register ?g "#_clj (user/go)")
(set-register ?b "#_clj (user/browse)")
#+end_src

* ox's paren magic
#+begin_src emacs-lisp
  (defun ox/open-round-insert ()
    (interactive)
    (paredit-open-round)
    (evil-insert 0))

  (show-paren-mode 1)

  (defun ox/toggle-parens--replace (pair start end)
    "Replace parens with a new PAIR at START and END in current buffer.
     A helper function for `toggle-parens'."
    (goto-char start)
    (delete-char 1)
    (insert (substring pair 0 1))
    (goto-char end)
    (delete-char 1)
    (insert (substring pair 1 2))
    (goto-char start))

  (defun ox/toggle-parens ()
    "Toggle parens () <> [] at cursor.
  Turn on `show-paren-mode' to see matching pairs of parentheses
  and other characters in buffers. This function then uses the same
  function `show-paren-data-function' to find and replace them with
  the other pair of brackets.
  This function can be easily modified and expanded to replace
  other brackets. Currently, mismatch information is ignored and
  mismatched parens are changed based on the left one."
    (interactive)
    (let* ((parens (funcall show-paren-data-function))
           (start (if (< (nth 0 parens) (nth 2 parens))
                      (nth 0 parens) (nth 2 parens)))
           (end (if (< (nth 0 parens) (nth 2 parens))
                    (nth 2 parens) (nth 0 parens)))
           (startchar (buffer-substring-no-properties start (1+ start)))
           (mismatch (nth 4 parens)))
      (when parens
        (pcase startchar
          ("(" (ox/toggle-parens--replace "[]" start end))
          ("[" (ox/toggle-parens--replace "{}" start end))
          ("{" (ox/toggle-parens--replace "()" start end))))))
#+end_src

* Uncategorised

These blocks need to find a home yet :)

#+begin_src emacs-lisp
(use-package git-gutter
  :config
  (global-git-gutter-mode +1))

(use-package html-to-hiccup
  :load-path "~/projects/html-to-hiccup")

(use-package caddyfile-mode
  :ensure t
  :mode (("Caddyfile\\'" . caddyfile-mode)
         ("caddy\\.conf\\'" . caddyfile-mode)))

(add-hook 'prog-mode-hook #'hs-minor-mode)
(add-hook 'clojure-mode-hook #'hs-minor-mode)
(add-hook 'emacs-lisp-mode-hook #'hs-minor-mode)

(setq scroll-step            1
      scroll-conservatively  10000)

(use-package flycheck
  :ensure t
  :init (global-flycheck-mode))

(use-package flycheck-clj-kondo
  :ensure t)

(use-package clojure-mode
  :ensure t
  :config
  (require 'flycheck-clj-kondo))

(use-package zprint-mode)

(use-package web-mode
  :custom
  (web-mode-markup-indent-offset 2)
  (web-mode-css-indent-offset 2)
  (web-mode-code-indent-offset 2)
  :init
  (setq-default
   indent-tabs-mode nil
   tab-width 2))
#+end_src

* Clojure

** cljr Refactoring

#+begin_src emacs-lisp

(use-package clj-refactor
  :after (cider)
  :diminish clj-refactor-mode
  :config
  (setq cljr-cljc-clojure-test-declaration "[clojure.test :refer [deftest testing is are use-fixtures run-tests join-fixtures]]"
        cljr-cljs-clojure-test-declaration "[clojure.test :refer [deftest testing is are use-fixtures run-tests join-fixtures]]"
        cljr-clojure-test-declaration "[clojure.test :refer [deftest testing is are use-fixtures run-tests join-fixtures]]"
        cljr-eagerly-build-asts-on-startup nil
        cljr-warn-on-eval nil)
  :hook ((clojurex-mode-hook
          clojurescript-mode-hook
          clojurec-mode-hook
          clojure-mode-hook)
         . clj-refactor-mode))

#+end_src

#+RESULTS:
| clj-refactor-mode |

** flow
#+begin_src emacs-lisp 
(defun cider-eval-clipboard-handler ()
  (nrepl-make-response-handler
   (current-buffer)
   (lambda (buffer value)
     (with-current-buffer buffer
       (with-temp-buffer
         (insert value)
         (clipboard-kill-region (point-min) (point-max)))))
   (lambda (_buffer out)
     (cider-emit-interactive-eval-output out))
   (lambda (_buffer err)
     (cider-emit-interactive-eval-err-output err))
   '()))

(defun cider-eval-last-sexpr-and-copy-to-clipboard ()
  (interactive)
  (cider-interactive-eval nil
                         (cider-eval-clipboard-handler)
                         (cider-last-sexp 'bounds)
                         (cider--nrepl-pr-request-map)))

(defun jet-pretty ()
  (interactive)
  (shell-command-on-region
   (region-beginning)
   (region-end)
   "jet --pretty --edn-reader-opts '{:default tagged-literal}'"
   (current-buffer)
   t
   "*jet error buffer*"
   t))
#+end_src

** re-org

*** from old config
 #+begin_src emacs-lisp
 (defun ss/wrap-with-spy ()
   (interactive)
   (cider-interactive-eval "(require 'sc.api)")
   (with-undo-amalgamate
     (symex-wrap)
     (insert "sc.api/spy ")
     (symex-mode-interface)
     (indent-for-tab-command)))

 (defun ss/rescope-last ()
   (interactive)
   (let ((ns (cider-current-ns t)))
     (cider-nrepl-sync-request:eval "(require 'sc.api)" nil ns)
     (cider-nrepl-sync-request:eval "(defmacro defsc*
                                 []
                               `(sc.api/defsc ~(sc.api/last-ep-id)))" nil ns)
     (cider-nrepl-sync-request:eval "(defsc*)" nil ns)))

 (defun ss/run-with-args (&optional rescope)
   (interactive)
   (with-undo-amalgamate
     (save-excursion
       (symex-goto-lowest)
       (symex-traverse-forward 2)
       (let ((fn-name (thing-at-point 'sexp t)))
         (symex-go-forward 1)
         (let* ((fn-args (thing-at-point 'sexp t))
                (fn-args-in (read-string (concat fn-name " " fn-args ": "))))
           (cider-nrepl-sync-request:eval (format "(%s %s)" fn-name fn-args-in)
                                          nil
                                          (cider-current-ns t))
           (when rescope (ss/re-scope-last)))))))

 (defun ss/run-with-args-and-rescope ()
   (interactive)
   (ss/run-with-args t))

 (defun ss/run-and-rescope-dwim* ()
   (interactive)
   (save-excursion
     (with-undo-amalgamate
       (ss/wrap-with-spy)
       (symex-evaluate-definition)
       ;; undo hack, not sure why it doesn't work w/o this.
       (insert ""))))

 (defun ss/run-and-rescope-dwim ()
   (interactive)
   (save-excursion
     (ss/run-and-rescope-dwim*)
     (evil-undo-pop)))

 (defun ss/instrument-spy* ()
   (interactive)
   (save-excursion
     (with-undo-amalgamate
       (ss/wrap-with-spy)
       (symex-evaluate-definition)
       ;; undo hack, not sure why it doesn't work w/o this.
       (symex-wrap))))

 (defun ss/instrument-spy ()
   (interactive)
   (let ((in-symex-mode (or (equal evil-state 'emacslike)
                            (equal evil-state 'normallike))))
     (save-excursion
       (ss/instrument-spy*)
       (evil-undo-pop))
     (when in-symex-mode
       (symex-mode-interface))))

 (defun signspice-with-mark (f &rest args)
   (interactive)
   (evil-set-jump)
   (setq signspice-last-jump (point))
   (apply f args))


 (defun signspice-yank-and-put-to-mark ()
   (interactive)
   (symex-yank 1)
   (goto-char signspice-last-jump)
   (symex-paste-after 1))


 (defun signspice-steal-from-ace ()
   (interactive)
   (let ((starting-point (point)))
     (lispy-ace-paren 2)
     (symex-yank 1)
     (goto-char starting-point)
     (symex-paste-after 1)))


 (defun signspice-eval-mark (char)
   (interactive (list (read-char "evaluate mark:")))
   (save-excursion
     (evil-goto-mark char)
     (symex-evaluate 1)))

 (defun portal.api/open ()
   (interactive)
   (cider-nrepl-sync-request:eval
    "(require 'portal.api) (def p (portal/open {:theme :portal.colors/solarized-light :portal.viewer/default :portal.viewer/tree})) (portal.api/tap)"))

 (defun portal-copy ()
   (interactive)
   (kill-new (nrepl-dict-get (cider-nrepl-sync-request:eval "@p") "value"))
   (symex-paste-after 1))

 (with-eval-after-load 'cider-mode
         (defun cider-tap (&rest r)
           (cons (concat "(let [__value "
                         (caar r)
                         "] (tap> (if (instance? clojure.lang.IObj __value)
                                (with-meta __value {:portal.viewer/default :portal.viewer/tree
                                                    :theme :portal.colors/solarized-light})
                                __value))
                        __value)")
                 (cdar r)))

         (advice-add 'cider-nrepl-request:eval
                     :filter-args #'cider-tap))

 (setq signspice-last-jump nil)

 (defun signspice-goto-previous-mark ()
   (interactive)
   (when (not signspice-last-jump)
     (setq signspice-last-jump (point)))
   (let ((pos (point))
         (last-pos signspice-last-jump))

     (goto-char last-pos)
     (setq signspice-last-jump pos)))


 (defun signspice-pprint-at-point ()
   (interactive)
   (unwind-protect
       (save-excursion
         (forward-sexp)
         (cider-pprint-eval-last-sexp))))

 (defun signspice-jsx->clj ()
   (interactive)
   (call-shell-region (point-min) (point-max) "node ~/projects/jsx-to-clojurescript/jsx-to-clojurescript.js --target om --ns n --kebab-tags" t t))


 (defun signspice-tsx->jsx ()
   (interactive)
   (call-shell-region (point-min) (point-max) ">> /tmp/temp.tsx; npx detype /tmp/temp.tsx /tmp/temp.jsx; cat /tmp/temp.jsx; rm /tmp/temp.tsx" t t))

 ;; (use-package popper
 ;;              :bind (("C-`"   . popper-toggle-latest)
 ;;                     ("M-`"   . popper-cycle)
 ;;                     ("C-M-`" . popper-toggle-type))
 ;;              :init
 ;;              (setq popper-reference-buffers
 ;;                    '("\\*Messages\\*"
 ;;                      "Output\\*$"
 ;;                      "\\*Async Shell Command\\*"
 ;;                      help-mode
 ;;                      compilation-mode
 ;;                      cider-repl-mode))
 ;;              (popper-mode +1)
 ;;              (popper-echo-mode +1))


 (use-package git-timemachine)

 #+end_src

** portal goodness
Credits to @Carlo from Slack -- modified
#+begin_src emacs-lisp
(defun open-portal-api ()
  (interactive)
  (cider-interactive-eval "(do (require 'portal.api)
                               (add-tap #'portal.api/submit)
                               (def portella (portal.api/open {:portal.viewer/default :portal.viewer/tree}))
                               (portal.api/tap))"))

(defun open-portal-web ()
  (interactive)
  (cider-interactive-eval "(do (require 'portal.web)
                               (add-tap #'portal.api/submit)
                               (def portella (portal.api/open {:theme :portal.colors/solarized-light :portal.viewer/default :portal.viewer/tree}))
                               (portal.api/tap))"))

(defun portal.api/clear ()
  (interactive)
  (cider-nrepl-sync-request:eval
   "(#?(:clj portal.api/clear :cljs portal.web/clear))"))

(defun portal/invoke-portal-command (command-str)
  (cider-nrepl-sync-request:eval
   (concat "(#?(:clj portal.api/eval-str :cljs portal.web/eval-str) \"" command-str "\")")))

(defmacro define-portal-command (command-name)
  (let ((emacs-command-name (intern (format "portal-ui-commands/%s" command-name)))
        (clojure-invocation (format "(portal.ui.commands/%s portal.ui.state/state)" command-name)))
    `(defun ,emacs-command-name ()
       (interactive)
       (portal/invoke-portal-command ,clojure-invocation))))

(define-portal-command select-root)
(define-portal-command select-next)
(define-portal-command select-prev)
(define-portal-command select-parent)
(define-portal-command select-child)
(define-portal-command history-back)
(define-portal-command toggle-expand)
(define-portal-command focus-selected)
(define-portal-command toggle-shell)
(define-portal-command toggle-shell)

(defun portal-copy ()
  (interactive)
  (insert (nrepl-dict-get (cider-nrepl-sync-request:eval "@portella") "value")))

(defun portal-ui-commands/set-viewer (viewer)
  (interactive)
  (portal/invoke-portal-command
   (concat
    "(require '[portal.ui.state :as s])

    (defn set-viewer! [viewer]
      (s/dispatch!
       s/state
       assoc-in
       [:selected-viewers
        (s/get-location
         (s/get-selected-context @s/state))]
       viewer))

    (set-viewer! :portal.viewer/" viewer ")")))

(defun portal-ui-commands/set-tree-viewer ()
  (interactive) (portal-ui-commands/set-viewer "tree"))

(defun portal-ui-commands/set-pprint-viewer ()
  (interactive) (portal-ui-commands/set-viewer "pprint"))

(defun portal-ui-commands/set-inspector-viewer ()
  (interactive) (portal-ui-commands/set-viewer "inspector"))

(with-eval-after-load 'clojure-mode
  (defhydra hydra-portal (clojure-mode-map "C-c C-c")
    "Portal"
    ("r" portal-ui-commands/select-root "Select root")
    ("s" portal-ui-commands/select-next "Select next")
    ("h" portal-ui-commands/select-prev "Select prev")
    ("k" portal-ui-commands/select-parent "Select parent")
    ("j" portal-ui-commands/select-child "Select child")
    ("n" portal-ui-commands/select-child "Select child")
    ("C-h" portal-ui-commands/history-back "History back")
    ("-" portal-ui-commands/focus-selected "Focus selected")
    ("e" portal-ui-commands/toggle-expand "Toggle expand")
    ("i" portal-ui-commands/set-inspector-viewer "Set inspector viewer")
    ("t" portal-ui-commands/set-tree-viewer "Set tree viewer")
    ("p" portal-ui-commands/set-pprint-viewer "Set pprint viewer")
    ("S" portal-ui-commands/toggle-shell "Toggle shell")
    ("c" portal-copy "Copy")
    (";" portal.api/clear "Clear")
    ("q" nil "Exit" :exit t)))

(defun portal-select-first ()
  (interactive)
  (portal-ui-commands/select-root)
  (portal-ui-commands/select-next)
  (hydra-portal/body))

(with-eval-after-load 'cider-mode
  (defun cider-tap (&rest r)
    (cons (concat "(let [__value " (caar r) "]"
                  " (tap> __value)
                     __value)")
          (cdar r)))

  (advice-add 'cider-nrepl-request:eval
              :filter-args #'cider-tap))


#+end_src

* LSP
#+begin_src emacs-lisp
(use-package lsp-mode
  :commands lsp
  :config

  ;; Core
  (setq lsp-headerline-breadcrumb-enable nil
        lsp-signature-render-documentation nil
        lsp-signature-function 'lsp-signature-posframe
        lsp-semantic-tokens-enable t
        lsp-idle-delay 0.3
        lsp-use-plists nil)
  (add-hook 'lsp-after-apply-edits-hook (lambda (&rest _) (save-buffer)))
  (add-hook 'lsp-mode-hook (lambda () (setq-local company-format-margin-function #'company-vscode-dark-icons-margin)))

  ;; Clojure lsp setup
  (let ((clojure-lsp-dev (expand-file-name "~/dev/clojure-lsp/clojure-lsp")))
    (when (file-exists-p clojure-lsp-dev)
      ;; clojure-lsp local development
      (setq lsp-clojure-custom-server-command `("bash" "-c" ,clojure-lsp-dev)
            lsp-completion-no-cache t
            lsp-completion-use-last-result nil))))

(use-package lsp-ui
  :after lsp-mode
  :commands lsp-ui-mode
  :config
  (setq lsp-ui-doc-enable nil
        lsp-ui-peek-enable nil))  

#+end_src


